sudo: required
services:
  - docker

before_install:
  - docker build -t cvilen/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true cvilen/react-test npm test

after_success:
  - docker build -t cvilen/multi-client ./client
  - docker build -t cvilen/multi-nginx ./nginx
  - docker build -t cvilen/multi-server ./server
  - docker build -t cvilen/multi-worker ./worker

  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push cvilen/multi-client
  - docker push cvilen/multi-nginx
  - docker push cvilen/multi-server
  - docker push cvilen/multi-worker